package ssm.bean;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.updatetime
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    private String updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.author
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.updatetime
     *
     * @return the value of news.updatetime
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.updatetime
     *
     * @param updatetime the value for news.updatetime
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.author
     *
     * @return the value of news.author
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.author
     *
     * @param author the value for news.author
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}