package ssm.bean;

import java.util.ArrayList;
import java.util.List;

public class TraderecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public TraderecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOtheraccountIsNull() {
            addCriterion("OtherAccount is null");
            return (Criteria) this;
        }

        public Criteria andOtheraccountIsNotNull() {
            addCriterion("OtherAccount is not null");
            return (Criteria) this;
        }

        public Criteria andOtheraccountEqualTo(String value) {
            addCriterion("OtherAccount =", value, "otheraccount");
            return (Criteria) this;
        }

        public Criteria andOtheraccountNotEqualTo(String value) {
            addCriterion("OtherAccount <>", value, "otheraccount");
            return (Criteria) this;
        }

        public Criteria andOtheraccountGreaterThan(String value) {
            addCriterion("OtherAccount >", value, "otheraccount");
            return (Criteria) this;
        }

        public Criteria andOtheraccountGreaterThanOrEqualTo(String value) {
            addCriterion("OtherAccount >=", value, "otheraccount");
            return (Criteria) this;
        }

        public Criteria andOtheraccountLessThan(String value) {
            addCriterion("OtherAccount <", value, "otheraccount");
            return (Criteria) this;
        }

        public Criteria andOtheraccountLessThanOrEqualTo(String value) {
            addCriterion("OtherAccount <=", value, "otheraccount");
            return (Criteria) this;
        }

        public Criteria andOtheraccountLike(String value) {
            addCriterion("OtherAccount like", value, "otheraccount");
            return (Criteria) this;
        }

        public Criteria andOtheraccountNotLike(String value) {
            addCriterion("OtherAccount not like", value, "otheraccount");
            return (Criteria) this;
        }

        public Criteria andOtheraccountIn(List<String> values) {
            addCriterion("OtherAccount in", values, "otheraccount");
            return (Criteria) this;
        }

        public Criteria andOtheraccountNotIn(List<String> values) {
            addCriterion("OtherAccount not in", values, "otheraccount");
            return (Criteria) this;
        }

        public Criteria andOtheraccountBetween(String value1, String value2) {
            addCriterion("OtherAccount between", value1, value2, "otheraccount");
            return (Criteria) this;
        }

        public Criteria andOtheraccountNotBetween(String value1, String value2) {
            addCriterion("OtherAccount not between", value1, value2, "otheraccount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountIsNull() {
            addCriterion("transaction_amount is null");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountIsNotNull() {
            addCriterion("transaction_amount is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountEqualTo(Double value) {
            addCriterion("transaction_amount =", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountNotEqualTo(Double value) {
            addCriterion("transaction_amount <>", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountGreaterThan(Double value) {
            addCriterion("transaction_amount >", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("transaction_amount >=", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountLessThan(Double value) {
            addCriterion("transaction_amount <", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountLessThanOrEqualTo(Double value) {
            addCriterion("transaction_amount <=", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountIn(List<Double> values) {
            addCriterion("transaction_amount in", values, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountNotIn(List<Double> values) {
            addCriterion("transaction_amount not in", values, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountBetween(Double value1, Double value2) {
            addCriterion("transaction_amount between", value1, value2, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountNotBetween(Double value1, Double value2) {
            addCriterion("transaction_amount not between", value1, value2, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTradetypIsNull() {
            addCriterion("tradeTyp is null");
            return (Criteria) this;
        }

        public Criteria andTradetypIsNotNull() {
            addCriterion("tradeTyp is not null");
            return (Criteria) this;
        }

        public Criteria andTradetypEqualTo(String value) {
            addCriterion("tradeTyp =", value, "tradetyp");
            return (Criteria) this;
        }

        public Criteria andTradetypNotEqualTo(String value) {
            addCriterion("tradeTyp <>", value, "tradetyp");
            return (Criteria) this;
        }

        public Criteria andTradetypGreaterThan(String value) {
            addCriterion("tradeTyp >", value, "tradetyp");
            return (Criteria) this;
        }

        public Criteria andTradetypGreaterThanOrEqualTo(String value) {
            addCriterion("tradeTyp >=", value, "tradetyp");
            return (Criteria) this;
        }

        public Criteria andTradetypLessThan(String value) {
            addCriterion("tradeTyp <", value, "tradetyp");
            return (Criteria) this;
        }

        public Criteria andTradetypLessThanOrEqualTo(String value) {
            addCriterion("tradeTyp <=", value, "tradetyp");
            return (Criteria) this;
        }

        public Criteria andTradetypLike(String value) {
            addCriterion("tradeTyp like", value, "tradetyp");
            return (Criteria) this;
        }

        public Criteria andTradetypNotLike(String value) {
            addCriterion("tradeTyp not like", value, "tradetyp");
            return (Criteria) this;
        }

        public Criteria andTradetypIn(List<String> values) {
            addCriterion("tradeTyp in", values, "tradetyp");
            return (Criteria) this;
        }

        public Criteria andTradetypNotIn(List<String> values) {
            addCriterion("tradeTyp not in", values, "tradetyp");
            return (Criteria) this;
        }

        public Criteria andTradetypBetween(String value1, String value2) {
            addCriterion("tradeTyp between", value1, value2, "tradetyp");
            return (Criteria) this;
        }

        public Criteria andTradetypNotBetween(String value1, String value2) {
            addCriterion("tradeTyp not between", value1, value2, "tradetyp");
            return (Criteria) this;
        }

        public Criteria andTradeTimeIsNull() {
            addCriterion("trade_time is null");
            return (Criteria) this;
        }

        public Criteria andTradeTimeIsNotNull() {
            addCriterion("trade_time is not null");
            return (Criteria) this;
        }

        public Criteria andTradeTimeEqualTo(String value) {
            addCriterion("trade_time =", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotEqualTo(String value) {
            addCriterion("trade_time <>", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeGreaterThan(String value) {
            addCriterion("trade_time >", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeGreaterThanOrEqualTo(String value) {
            addCriterion("trade_time >=", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeLessThan(String value) {
            addCriterion("trade_time <", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeLessThanOrEqualTo(String value) {
            addCriterion("trade_time <=", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeLike(String value) {
            addCriterion("trade_time like", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotLike(String value) {
            addCriterion("trade_time not like", value, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeIn(List<String> values) {
            addCriterion("trade_time in", values, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotIn(List<String> values) {
            addCriterion("trade_time not in", values, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeBetween(String value1, String value2) {
            addCriterion("trade_time between", value1, value2, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andTradeTimeNotBetween(String value1, String value2) {
            addCriterion("trade_time not between", value1, value2, "tradeTime");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table traderecord
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 16 20:56:40 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}