package ssm.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ssm.bean.Traderecord;
import ssm.bean.TraderecordExample;

public interface TraderecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    long countByExample(TraderecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    int deleteByExample(TraderecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    int insert(Traderecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    int insertSelective(Traderecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    List<Traderecord> selectByExample(TraderecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    Traderecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") Traderecord record, @Param("example") TraderecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    int updateByExample(@Param("record") Traderecord record, @Param("example") TraderecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    int updateByPrimaryKeySelective(Traderecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traderecord
     *
     * @mbg.generated Fri Oct 16 20:56:40 CST 2020
     */
    int updateByPrimaryKey(Traderecord record);
}