package ssm.bean;

public class Customer {
    @Override
	public String toString() {
		return "Customer [id=" + id + ", account=" + account + ", password=" + password + ", username=" + username
				+ ", birthday=" + birthday + ", sex=" + sex + ", homeAddress=" + homeAddress + ", phoneNumber="
				+ phoneNumber + ", sfz=" + sfz + ", balance=" + balance + ", email=" + email + ", status=" + status
				+ "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.account
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.password
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.username
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.birthDay
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.sex
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.Home_Address
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    private String homeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.Phone_number
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.sfz
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    private String sfz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.balance
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.email
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.status
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.account
     *
     * @return the value of customer.account
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.account
     *
     * @param account the value for customer.account
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.password
     *
     * @return the value of customer.password
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.password
     *
     * @param password the value for customer.password
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.username
     *
     * @return the value of customer.username
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.username
     *
     * @param username the value for customer.username
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.birthDay
     *
     * @return the value of customer.birthDay
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.birthDay
     *
     * @param birthday the value for customer.birthDay
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.sex
     *
     * @return the value of customer.sex
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.sex
     *
     * @param sex the value for customer.sex
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.Home_Address
     *
     * @return the value of customer.Home_Address
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.Home_Address
     *
     * @param homeAddress the value for customer.Home_Address
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.Phone_number
     *
     * @return the value of customer.Phone_number
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.Phone_number
     *
     * @param phoneNumber the value for customer.Phone_number
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.sfz
     *
     * @return the value of customer.sfz
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public String getSfz() {
        return sfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.sfz
     *
     * @param sfz the value for customer.sfz
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public void setSfz(String sfz) {
        this.sfz = sfz == null ? null : sfz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.balance
     *
     * @return the value of customer.balance
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.balance
     *
     * @param balance the value for customer.balance
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.email
     *
     * @return the value of customer.email
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.email
     *
     * @param email the value for customer.email
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.status
     *
     * @return the value of customer.status
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.status
     *
     * @param status the value for customer.status
     *
     * @mbg.generated Wed Oct 14 22:15:16 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}